name: Configure GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure GitHub Pages
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pages \
          -d '{"source":{"branch":"gh-pages","path":"/"}}' 